# --color=auto requires coreutils
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls --color=auto -al'
alias la='ls --color=auto -a'
alias l='ls --color=auto'
alias find='find -L'
alias cd='cd -P'
