# --color=auto requires coreutils
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls --color=auto -alF'
alias la='ls --color=auto -aF'
alias l='ls --color=auto -F'
alias find='find -L'
alias cd='cd -P'
