# --color=auto requires coreutils
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls --color=auto -al'
alias la='ls --color=auto -a'
alias l='ls --color=auto'
alias find='find -L'
alias cd='cd -P'
alias k=kubectl
alias kgp='kubectl get pods -o wide'
alias kgpw='kubectl get pods -o wide -w'
alias kgn='kubectl get nodes'
alias kgnw='kubectl get nodes -w'
alias agp='ag --perl'
alias prodmqmon='for x in 1 2 3; do ssh -n -N -L 1567$x:localhost:15672 root@p$x-bgdispatch.ex.retailops.com & done'