(global-unset-key (kbd "s-&"))
(global-unset-key (kbd "s-'"))
(global-unset-key (kbd "s-+"))
(global-unset-key (kbd "s-,"))
(global-unset-key (kbd "s--"))
(global-unset-key (kbd "s-0"))
(global-unset-key (kbd "s-:"))
(global-unset-key (kbd "s-="))
(global-unset-key (kbd "s-?"))
(global-unset-key (kbd "s-C"))
(global-unset-key (kbd "s-D"))
(global-unset-key (kbd "s-E"))
(global-unset-key (kbd "s-H"))
(global-unset-key (kbd "s-L"))
(global-unset-key (kbd "s-M"))
(global-unset-key (kbd "s-S"))
(global-unset-key (kbd "s-^"))
(global-unset-key (kbd "s-`"))
(global-unset-key (kbd "s-a"))
(global-unset-key (kbd "s-f"))
(global-unset-key (kbd "s-h"))
(global-unset-key (kbd "s-k"))
(global-unset-key (kbd "s-l"))
(global-unset-key (kbd "s-n"))
(global-unset-key (kbd "s-o"))
(global-unset-key (kbd "s-q"))
(global-unset-key (kbd "s-t"))
(global-unset-key (kbd "s-u"))
(global-unset-key (kbd "s-v"))
(global-unset-key (kbd "s-w"))
(global-unset-key (kbd "s-x"))
(global-unset-key (kbd "s-y"))
(global-unset-key (kbd "s-z"))
(global-unset-key (kbd "s-|"))
(global-unset-key (kbd "s-~"))

(global-set-key (kbd "<backtab>") 'indent-rigidly)
(global-set-key (kbd "C-SPC") 'set-mark-command)

(global-set-key (kbd "C-r") 'swiper-isearch-backward)
(global-set-key (kbd "C-s") 'swiper-isearch)
(global-set-key (kbd "C-z") 'scroll-one-line-up)
(global-set-key (kbd "C--") 'undo)
(global-unset-key (kbd "C-h"))
(global-set-key (kbd "C-h") 'backward-delete-char)
(global-unset-key (kbd "DEL"))
(global-set-key (kbd "DEL") 'backward-delete-char)
;; Translate the problematic keys to the function key Hyper:
(define-key input-decode-map (kbd "C-i") (kbd "H-i"))
;; Rebind then accordantly:
(global-set-key (kbd "H-i") 'counsel-imenu)

(global-set-key (kbd "M-c") 'backward-capitalize-word)
(global-set-key (kbd "M-l") 'backward-downcase-word)
(global-set-key (kbd "M-u") 'backward-upcase-word)
(global-set-key (kbd "M-h") 'backward-kill-word)
(global-set-key (kbd "M-z") 'scroll-one-line-down)
(global-set-key (kbd "M-'") 'dabbrev-expand)
(global-set-key (kbd "M-%") 'query-replace-regexp)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "M-y") 'counsel-yank-pop)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)

(global-set-key (kbd "C-x l") 'goto-line)
(global-set-key (kbd "C-x n") 'gosmacs-next-window)
(global-set-key (kbd "C-x p") 'gosmacs-previous-window)
(global-set-key (kbd "C-x b") 'ivy-switch-buffer)
;; (global-set-key (kbd "C-x RET") 'term-shell)
;; (global-set-key (kbd "C-x RET") 'shell)
(global-set-key (kbd "C-x RET") 'assert-vterm)

(global-set-key (kbd "M-C-m") 'magit-status)

(global-unset-key (kbd "s-r"))
(define-prefix-command 's-r-map)
(global-set-key (kbd "s-r") 's-r-map)
(global-set-key (kbd "s-r s") 'copy-to-register)
(global-set-key (kbd "s-r r") 'copy-rectangle-to-register)
(global-set-key (kbd "s-r i") 'insert-register)
(global-set-key (kbd "s-r SPC") 'point-to-register)
(global-set-key (kbd "s-r j") 'jump-to-register)
(global-set-key (kbd "s-r w") 'window-configuration-to-register)
(global-set-key (kbd "s-r f") 'frameset-to-register)
(global-set-key (kbd "s-r n") 'number-to-register)
(global-set-key (kbd "s-r +") 'increment-register)
(global-set-key (kbd "s-r a") 'append-to-register)
(global-set-key (kbd "s-r p") 'prepend-to-register)
(global-set-key (kbd "s-r k") 'kmacro-to-register)

(global-unset-key (kbd "s-s"))
(define-prefix-command 's-s-map)
(global-set-key (kbd "s-s") 's-s-map)
(global-set-key (kbd "s-s g") 'grep)
(global-set-key (kbd "s-s r") 'rgrep)

(define-prefix-command 'help)
(global-set-key (kbd "C-/") 'help)
(global-set-key (kbd "C-c C-/") 'help)
(eval-after-load 'cperl-mode
  '(progn
     (define-key cperl-mode-map (kbd "C-/ f") 'cperl-info-on-current-command)
     (define-key cperl-mode-map (kbd "C-c C-/ F") 'cperl-info-on-command)
     (define-key cperl-mode-map (kbd "C-c C-/ P") 'cperl-perldoc-at-point)
     (define-key cperl-mode-map (kbd "C-c C-/ a") 'cperl-toggle-autohelp)
     (define-key cperl-mode-map (kbd "C-c C-/ f") 'cperl-info-on-command)
     (define-key cperl-mode-map (kbd "C-c C-/ p") 'cperl-perldoc)
     (define-key cperl-mode-map (kbd "C-c C-/ v") 'cperl-get-help)
     (define-key cperl-mode-map (kbd "C-h") nil)))

(eval-after-load "shell"
  '(progn
     (define-key shell-mode-map (kbd "C-c c") 'dirs)
     (define-key shell-mode-map (kbd "C-c f") 'find-file-at-point)
     (define-key shell-mode-map (kbd "C-j") 'term-switch-to-shell-mode)))

;; (eval-after-load "term"
;;   '(progn
;;      (define-key term-raw-map (kbd "C-x C-j") 'term-toggle-input-mode)
;;      (define-key term-raw-map (kbd "s-v") 'term-paste)
;;      (define-key term-mode-map (kbd "C-x C-j") 'term-toggle-input-mode)
;;      (define-key term-mode-map (kbd "C-c f") 'find-file-at-point)))
